<template>
  <h2>Company Dashboard</h2>
  <div v-if="message" class="alert alert-info">{{message}}</div>
  <div class="row g-3 mb-4"><div v-for="(value,label) in stats" :key="label" class="col-6 col-md-3"><div class="card"><div class="card-body text-center"><h3>{{value}}</h3><span class="text-capitalize">{{label.replace('_',' ')}}</span></div></div></div></div>
  <div class="card mb-3"><div class="card-body"><h4>Company Profile</h4><form class="row" @submit.prevent="saveProfile"><div v-for="field in ['name','industry','location','hr_contact','website']" :key="field" class="col-md-4"><label class="form-label text-capitalize">{{field.replace('_',' ')}}</label><input v-model="profile[field]" class="form-control mb-2" :required="field!=='website'"></div><div><button class="btn btn-secondary">Save Profile</button></div></form></div></div>
  <div v-if="stats.approval_status!=='Approved'" class="alert alert-warning">Drive creation is locked until admin approval. Current status: {{stats.approval_status}}</div>
  <div v-else class="card mb-3"><div class="card-body"><h4>Create Drive</h4><form class="row" @submit.prevent="createDrive"><div v-for="field in fields" :key="field.key" class="col-md-4"><label class="form-label">{{field.label}}</label><input v-model="form[field.key]" :type="field.type||'text'" :step="field.type==='number'?'any':undefined" class="form-control mb-2" required></div><div class="col-12"><label class="form-label">Description</label><textarea v-model="form.description" class="form-control mb-2" required></textarea><button class="btn btn-primary">Create Drive</button></div></form></div></div>
  <h4>Your Drives</h4><div class="table-responsive"><table class="table table-bordered"><thead><tr><th>Title</th><th>Status</th><th>Applicants</th><th>Actions</th></tr></thead><tbody><tr v-for="d in drives" :key="d.id"><td>{{d.title}}</td><td>{{d.status}}</td><td>{{d.applicants}}</td><td><button class="btn btn-outline-primary btn-sm me-1" @click="showApplicants(d.id)">Applicants</button><button v-if="['Approved','Active','Closed'].includes(d.status)" class="btn btn-outline-dark btn-sm" @click="updateDrive(d.id,d.status==='Closed'?'Active':'Closed')">{{d.status==='Closed'?'Activate':'Close'}}</button></td></tr></tbody></table></div>
  <div v-if="applicants.length"><h4>Applicants</h4><div v-for="a in applicants" :key="a.application_id" class="card mb-2"><div class="card-body"><b>{{a.student.name}}</b> ({{a.student.student_code}}) — {{a.student.branch}}, CGPA {{a.student.cgpa}}<p>Skills: {{a.student.skills||'Not added'}}</p><select v-model="a.status" class="form-select d-inline-block me-2" style="width:170px"><option v-for="s in statuses" :key="s">{{s}}</option></select><input v-model="a.feedback" class="form-control d-inline-block me-2" style="max-width:300px" placeholder="Feedback"><button class="btn btn-primary btn-sm" @click="saveApplication(a)">Save</button><details class="mt-2"><summary>Schedule interview</summary><div class="row mt-2"><input v-model="a.when" type="datetime-local" class="form-control col m-1"><input v-model="a.mode" placeholder="Mode" class="form-control col m-1"><input v-model="a.details" placeholder="Link or venue" class="form-control col m-1"><button class="btn btn-secondary col m-1" @click="interview(a)">Schedule</button></div></details></div></div></div>
</template>
<script setup>
import { onMounted, reactive, ref } from 'vue'; import api from '../api'
const stats=ref({}); const profile=reactive({}); const drives=ref([]); const applicants=ref([]); const message=ref(''); const form=reactive({}); const statuses=['Applied','Shortlisted','Interview','Selected','Rejected','Placed']
const fields=[{key:'title',label:'Job Title'},{key:'required_skills',label:'Required Skills'},{key:'experience',label:'Experience'},{key:'salary',label:'Salary',type:'number'},{key:'benefits',label:'Benefits'},{key:'eligible_branch',label:'Eligible Branch'},{key:'minimum_cgpa',label:'Minimum CGPA',type:'number'},{key:'graduation_year',label:'Graduation Year',type:'number'},{key:'application_deadline',label:'Deadline',type:'datetime-local'}]
async function load(){stats.value=(await api.get('/company/dashboard')).data; Object.assign(profile,(await api.get('/company/profile')).data.company); drives.value=(await api.get('/company/drives')).data.drives}
async function saveProfile(){await api.patch('/company/profile',profile); message.value='Profile saved'}
async function createDrive(){message.value=(await api.post('/company/drives',form)).data.message; Object.keys(form).forEach(k=>delete form[k]); await load()}
async function updateDrive(id,status){message.value=(await api.patch(`/company/drives/${id}`,{status})).data.message; await load()}
async function showApplicants(id){applicants.value=(await api.get(`/company/drives/${id}/applicants`)).data.applicants}
async function saveApplication(a){message.value=(await api.patch(`/company/applications/${a.application_id}`,{status:a.status,feedback:a.feedback})).data.message}
async function interview(a){message.value=(await api.post(`/company/applications/${a.application_id}/interview`,{scheduled_at:a.when,mode:a.mode,meeting_details:a.details})).data.message}
onMounted(load)
</script>
